bin_NAMES = test

test_SRCS = test.c \
	   		test_util.c \
	   		test_hello.c \
	   		test_esbl_alg.c \
            test_esbl_list.c \
            test_esbl_vect.c \
            test_esbl_htbl.c \
			test_lang_lex.c  \
			test_lang_val.c  \
			test_lang_parse.c


test_CPPFLAGS = -I../cunit
test_CFLAGS   =
test_LDFLAGS  = -lcunit -lesbl -llang

