bin_NAMES = test

test_SRCS = test.c \
	   		test_util.c \
	   		test_hello.c \
			test_lang_lex.c  \
			test_lang_val.c  \
			test_lang_parse.c \
			test_lang_symtbl.c \
			test_lang_exec.c


test_CPPFLAGS = -I../cunit
test_CFLAGS   =
test_LDFLAGS  = -lcunit -lsal -llang

