bin_NAMES = panda

panda_SRCS = main.c dump.c interactive.c interpreter.c compile.c native.c

panda_CPPFLAGS = -I${BASE}
panda_CFLAGS   = -g
panda_LDFLAGS  = -L${BASE}/sal -L${BASE}/lang -lsal -llang -lreadline

