lib_NAMES = lang

lang_SRCS = heap.c \
			ast.c \
			env.c\
			lex.c \
			parse.c \
			bcode.c \
			compile.c\
			executable.c \
			interp.c \
			object.c \
			function.c \
			array.c \
			string.c

lang_CPPFLAGS = -I${BASE} -Wall -Werror
lang_CFLAGS   = -g
lang_LDFLAGS  =

