# Makefile.pub
#
# Copyright (C) 2016 ding.lixing@gmail.com
#
# public make rules
# user should not modify anything there

include Makefile

AS  := ${PREFIX}as
CC 	:= ${PREFIX}gcc
LD  := ${PREFIX}gcc
AR  := ${PREFIX}ar
RM  := rm -rf
MAKE := make

# Marco build_obj_rule
# param ${1}: source file
# param ${2}: program or library name
define build_obj_rule
${1:%.c=%.o}: ${1}
	@printf "[CC]\t$$@\n"
	@${CC} ${TGT_CPPFLAGS} ${${2}_CPPFLAGS} ${TGT_CFLAGS} ${${2}_CFLAGS} -MD -c $$< -o $$@
endef

# Marco build_prog_rule
# param ${1}: program name
define build_prog_rule
${1}_OBJS = ${${1}_SRCS:%.c=%.o}
${1}_DEPS = ${${1}_SRCS:%.c=%.d}
${1}: $${${1}_OBJS}
	@printf "[LD]\t$$@\n"
	@${LD} -o $$@ $${${1}_OBJS} ${TGT_LDFLAGS} $${${1}_LDFLAGS}

${1}.clean:
	@${RM} $${${1}_OBJS}
	@${RM} $${${1}_DEPS}
	@${RM} ${1}

$(foreach src,${${1}_SRCS},$(eval $(call build_obj_rule,${src},${1})))
-include $${${1}_DEPS}
endef

# Marco build_lib_rule
# param ${1}: library name
define build_lib_rule
${1}_OBJS = ${${1}_SRCS:%.c=%.o}
${1}_DEPS = ${${1}_SRCS:%.c=%.d}
${1}: lib${1}.a

lib${1}.a: $${${1}_OBJS}
	@printf "[AR]\t$$@\n"
	@${AR} rcs lib${1}.a $${${1}_OBJS}

${1}.clean:
	@${RM} $${${1}_OBJS}
	@${RM} $${${1}_DEPS}
	@${RM} lib${1}.a

$(foreach src,${${1}_SRCS},$(eval $(call build_obj_rule,${src},${1})))
-include $${${1}_DEPS}
endef

all: bin lib

bin: ${bin_NAMES}

lib: ${lib_NAMES}

clean: ${bin_NAMES:%=%.clean} ${lib_NAMES:%=%.clean}

$(foreach prog,${bin_NAMES},$(eval $(call build_prog_rule,${prog})))

$(foreach lib,${lib_NAMES},$(eval $(call build_lib_rule,${lib})))

.PHONY: clean bin lib all

