## GPLv2 License
##
## Copyright (C) 2016-2018 Lixing Ding <ding.lixing@gmail.com>
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

AS  := ${PREFIX}as
CC 	:= ${PREFIX}gcc
LD  := ${PREFIX}gcc
AR  := ${PREFIX}ar
RM  := rm -rf
MAKE := make

# Marco build_obj_rule
# param ${1}: source file
# param ${2}: program or library name
define build_obj_rule
${1:%.c=%.o}: ${1}
	@printf "[CC]\t$$@\n"
	@${CC} ${TGT_CPPFLAGS} ${${2}_CPPFLAGS} ${TGT_CFLAGS} ${${2}_CFLAGS} -MD -c $$< -o $$@
endef

# Marco build_prog_rule
# param ${1}: program name
define build_prog_rule
${1}_OBJS = ${${1}_SRCS:%.c=%.o}
${1}_DEPS = ${${1}_SRCS:%.c=%.d}
${1}: $${${1}_OBJS}
	@printf "[LD]\t$$@\n"
	@${LD} -o $$@ $${${1}_OBJS} ${TGT_LDFLAGS} $${${1}_LDFLAGS}

${1}.clean:
	@${RM} $${${1}_OBJS}
	@${RM} $${${1}_DEPS}
	@${RM} ${1}

$(foreach src,${${1}_SRCS},$(eval $(call build_obj_rule,${src},${1})))
-include $${${1}_DEPS}
endef

# Marco build_lib_rule
# param ${1}: library name
define build_lib_rule
${1}_OBJS = ${${1}_SRCS:%.c=%.o}
${1}_DEPS = ${${1}_SRCS:%.c=%.d}
${1}: lib${1}.a

lib${1}.a: $${${1}_OBJS}
	@printf "[AR]\t$$@\n"
	@${AR} rcs lib${1}.a $${${1}_OBJS}

${1}.clean:
	@${RM} $${${1}_OBJS}
	@${RM} $${${1}_DEPS}
	@${RM} lib${1}.a

$(foreach src,${${1}_SRCS},$(eval $(call build_obj_rule,${src},${1})))
-include $${${1}_DEPS}
endef

$(info ${lib_NAMES} ${PWD})
all: lib bin

lib: ${lib_NAMES}

bin: ${bin_NAMES}

clean: ${bin_NAMES:%=%.clean} ${lib_NAMES:%=%.clean}

$(foreach lib,${lib_NAMES},$(eval $(call build_lib_rule,${lib})))

$(foreach bin,${bin_NAMES},$(eval $(call build_prog_rule,${bin})))

.PHONY: clean bin lib all

